interest-protocol/sui-coins

components/layout/index.tsx
views/components/pool-title-bar/index.tsx
views/create-pool/create-pool-form/create-pool-form-select-dex.tsx
views/create-pool/create-pool-form/index.tsx
views/create-pool/index.tsx
views/pool-details/index.tsx
views/pool-details/pool-form/deposit.tsx
views/pool-details/pool-form/index.tsx
views/pool-details/pool-form/withdraw.tsx
views/pool-details/pool-transaction/components/card-wrapper/index.tsx
views/pool-details/pool-transaction/index.tsx
views/pools/header/action-group.tsx
views/pools/index.tsx

---
- https://app.asana.com/0/0/1206250953909087

:lipstick: refactor: New Pool

---

package.json
views/swap/swap-button.tsx
yarn.lock

---
- https://app.asana.com/0/0/1206303996321792

:lipstick: change modals

---

views/components/select-nft-modal/nft-modal-item.tsx

---
- https://app.asana.com/0/0/1206536111880034

:dizzy: add loader for nft images

---

views/metrics/top-tables/top-coins-table/top-pools-table-body.tsx
views/metrics/top-tables/top-pools-table/top-pools-table-body.tsx
views/metrics/top-tables/top-table-skeleton.tsx

---
- https://app.asana.com/0/0/1206536111880029

:lipstick: Metrics skeleton

---

package.json
pages/api/v1/metrics/get-daily-volume.ts
views/metrics/components/chart-wrapper/chart.types.ts
views/metrics/components/chart-wrapper/header.tsx
views/metrics/components/chart-wrapper/index.tsx
views/metrics/daily-volume/index.tsx
views/metrics/index.tsx
views/metrics/metrics.types.ts
yarn.lock

---
- https://app.asana.com/0/0/1206536112877315

:sparkles: New daily volume

---

pages/api/v1/metrics/get-tvl-by-pool.ts
styles/index.ts
views/metrics/components/chart-wrapper/chart.types.ts
views/metrics/components/chart-wrapper/header.tsx
views/metrics/components/chart-wrapper/index.tsx
views/metrics/index.tsx
views/metrics/metrics.types.ts
views/metrics/top-tables/top-pools-table/top-pools-table-body.tsx
views/metrics/tvl-pools/index.tsx
views/metrics/tvl-pools/tvl-pools.data.ts

---
- https://app.asana.com/0/0/1206536112877301

:sparkles: New tvl pools

---

pages/api/v1/metrics/get-total-liquidity.ts
views/metrics/components/chart-wrapper/header.tsx
views/metrics/index.tsx
views/metrics/total-liquidity/index.tsx

---
- https://app.asana.com/0/0/1206536111880017

:sparkles: New Total Liquidity charts

---

pages/index.tsx
views/swap/input/dollar-value.tsx
views/swap/input/index.tsx
views/swap/input/select-token.tsx
views/swap/input/slider.tsx
views/swap/preview-swap-button.tsx
views/swap/swap-button.tsx
views/swap/swap-flip-token.tsx
views/swap/swap-preview-modal/index.tsx
views/swap/swap-preview-modal/swap-preview-modal-summary.tsx
views/swap/swap-update-price.tsx
views/swap/swap.types.ts

---
- https://app.asana.com/0/0/1206859474795572

🐛  fix big number value

---

views/swap/input/slider.tsx

---
- https://app.asana.com/0/0/1206859474795566

:bug: Re-render fixed bug on formula

---

views/swap/swap-flip-token.tsx
yarn.lock

---
- https://app.asana.com/0/0/1206886479884317

:bug: Fix button background when clicked

---

views/swap/swap-preview-modal/index.tsx

---
- https://app.asana.com/0/0/1206859474951521

:lipstick: Resize on swap preview modal

---

pages/index.tsx

---
- https://app.asana.com/0/0/1206901855045497

🐛  Fix select same icon by url

---

views/create-token/create-token-form/upload-image.tsx

---
- https://app.asana.com/0/0/1206886483847810

:bug: Fix log message to upload file

---

utils/string/index.ts

---
- https://app.asana.com/0/0/1206901855045503

🐛  Fix prevent negative values

---

components/wallet/profile/menu-profile/profile-item.tsx

---
- https://app.asana.com/0/0/1206886483847814

🐛  Fix profile icons with same disabled color

---

views/swap/input/slider.tsx

---
- https://app.asana.com/0/0/1206901855045476

🐛  Fix slider initial position

---

views/swap/swap-path/index.tsx

---
- https://app.asana.com/0/0/1206901855045491

:lipstick: Aftermath route math fixed

---

package.json
yarn.lock

---
- https://app.asana.com/0/0/1206886483847844

:bug: Fix dialog modal width on mobile

---

views/send/send-history/send-history-table.tsx

---
- https://app.asana.com/0/0/1207016599703397

:lipstick: Remove page number on loading and not found history

---

components/account-info/menu-options/menu-option.types.ts
components/account-info/menu-options/option-item.tsx
components/account-info/sui-network.tsx

---
- https://app.asana.com/0/0/1207026050585967

:bug: fix: border style in dropdown

---

context/web3-manager/index.tsx
views/create-token/create-token-form/index.tsx

---
- https://app.asana.com/0/0/1207084328698934
- https://app.asana.com/0/0/1207084328698941

🐛 : Fix dialog mutate object

---

views/incinerator/body/table.tsx
views/incinerator/filter-tabs.tsx
views/incinerator/header.tsx
views/incinerator/incinerator.data.ts
views/incinerator/incinerator.types.ts
views/incinerator/index.tsx

---
- https://app.asana.com/0/0/1207165001947407

:sparkles: Incinerator tabs

---

views/incinerator/incinerator-table/burn-button.tsx
views/incinerator/incinerator-table/index.tsx
views/incinerator/incinerator-table/table-header.tsx
views/incinerator/index.tsx

---
- https://app.asana.com/0/0/1207165001947425

:sparkles: Incinerator dialog

---

views/send/send-history/send-history-table.tsx

---
- https://app.asana.com/0/0/1207079774186103

:lipstick: adjust the button action on history

---

views/incinerator/incinerator-tabs.tsx

---
- https://app.asana.com/0/0/1207217181047596

✨ Selected tab switch animation

---

views/incinerator/incinerator-table/incinerator-table-body/incinerator-table-maybe-input/index.tsx
views/incinerator/incinerator-table/incinerator-table-body/incinerator-table-row.tsx

---
- https://app.asana.com/0/0/1207217181047582

:bug: Table numeric row font size

---

components/svg/search.tsx

---
- https://app.asana.com/0/0/1207217180335946

♻️ Refactor incinerator search icon

---

views/incinerator/incinerator-tabs.tsx

---
- https://app.asana.com/0/0/1207234925955544

:sparkles: Add tabs border bottom

---

views/incinerator/component/incinerator-token-object/index.tsx
views/incinerator/incinerator-button/index.tsx
views/incinerator/incinerator-table/incinerator-table-body/incinerator-table-row.tsx

---
- https://app.asana.com/0/0/1207217181047590

:lipstick: Adding token icon on modal

---

utils/string/index.ts

---
- https://app.asana.com/0/0/1207230417776240

:bug: Logic to check kind object changed

---

views/incinerator/incinerator-table/incinerator-table-body/incinerator-table-maybe-input/incinerator-table-input.tsx

---
- https://app.asana.com/0/0/1207280625001287

:bug: fix: escape event

---

views/incinerator/incinerator-table/incinerator-table-body/incinerator-table-maybe-input/incinerator-table-input.tsx
views/incinerator/incinerator-table/incinerator-table-body/incinerator-table-row.tsx

---
- https://app.asana.com/0/0/1207280625001292

:sparkles: Button max added on field

---

views/pool-details/pool-info/components/accordion/accordion.types.ts
views/pool-details/pool-info/components/accordion/index.tsx
views/pool-details/pool-info/components/accordion/item-standard-skeleton.tsx
views/pool-details/pool-info/index.tsx
views/pool-details/pool-info/pool-info-advanced.tsx
views/pool-details/pool-info/pool-info-detail.tsx
views/pool-details/pool-info/pool-info-loading.tsx

---
- https://app.asana.com/0/0/1207292193356149

:sparkles: Skeleton on Pool Details

---

components/layout/sidebar/menu-item/menu-item-title.tsx

---
- https://app.asana.com/0/0/1207294954348123

:bug: Fix sidebar tooltip

---

views/pool-details/pool-form/index.tsx
views/pool-details/pool-info/components/accordion/index.tsx

---
- https://app.asana.com/0/0/1207292193356156

:bug: Tooltip in pool details fixed

---

context/network/index.tsx

---
- https://app.asana.com/0/0/1207294954348138

:bug: Fix refresh network

---

views/swap/swap-header.tsx
views/swap/swap-select-aggregator-modal.tsx
views/swap/swap.data.ts
views/swap/swap.types.ts

---
- https://app.asana.com/0/0/1207300212690710

:sparkles: Adding select aggregator modal

---

components/svg/index.ts
components/svg/subtract-box.tsx
views/swap/index.tsx
views/swap/input/balance.tsx
views/swap/input/dollar-value.tsx
views/swap/input/header-info.tsx
views/swap/input/index.tsx
views/swap/input/price-impact.tsx
views/swap/input/select-token.tsx
views/swap/swap-preview-modal/index.tsx
views/swap/swap-preview-modal/swap-preview-modal-summary.tsx
views/swap/swap-update-price.tsx

---
- https://app.asana.com/0/0/1207300212690718

:sparkles: New inputs ui

---

views/pool-details/pool-form/pool-field/index.tsx
views/pool-details/pool-info/components/detail-tabs/index.tsx
views/pool-details/pool-info/components/detail-tabs/pool-details-tabs-item.tsx
views/pool-details/pool-info/components/detail-tabs/pool-details-tabs.types.ts

---
- https://app.asana.com/0/0/1207294954348133

:recycle: Add pools tabs animations

---

components/svg/dot-error.tsx
pages/index.tsx
views/swap/input/from-input.tsx
views/swap/manage-slippage/manage-slippage-form/index.tsx
views/swap/preview-swap-button.tsx
views/swap/swap-button.tsx
views/swap/swap-header.tsx
views/swap/swap-init-manager.tsx
views/swap/swap-messages.tsx
views/swap/swap-powered-by.tsx
views/swap/swap-update-price.tsx
views/swap/swap.data.ts
views/swap/swap.types.ts

---
- https://app.asana.com/0/0/1207313499882251

:sparkles: Swap aggregator settings

---

views/pools/pool-card/pool-card-trade.tsx
views/pools/pool-card/pool-card.types.ts
views/pools/pool-filter/dropdown/index.tsx
views/pools/pool-filter/index.tsx
views/pools/pool-filter/pool-filter.data.ts
views/pools/pools.types.ts

---
- https://app.asana.com/0/0/1207314109375444

:fix: Close  dropdown when  clicked outside

---

views/incinerator/incinerator-manager.tsx
views/incinerator/incinerator-table/incinerator-table-body/incinerator-table-row.tsx

---
- https://app.asana.com/0/0/1207353946918392

:bug: Incinerator manager bug fixed

---

views/incinerator/incinerator-burn-scams.tsx
views/incinerator/incinerator-token-object.tsx

---
- https://app.asana.com/0/0/1207603274659584

🐛  Fix burn scam button

---

components/layout/sidebar/index.tsx
components/layout/sidebar/menu-item/index.tsx
components/layout/sidebar/menu-list.tsx
components/layout/sidebar/sidebar.types.ts

---
- https://app.asana.com/0/0/1207618141752784

:bug: Sidebar bug on openning solved

---

components/layout/index.tsx

---
- https://app.asana.com/0/0/1207860054381034

:lipstick: Added scroll bar on the right

---

views/swap/swap-preview-modal/index.tsx

---
- https://app.asana.com/0/0/1207855694481554

:bug: Fix button hover

---

views/swap/preview-swap-button.tsx
views/swap/swap-update-price.tsx

---
- https://app.asana.com/0/0/1207891812328889

:bug: Swap message doesnt update errors

---

components/layout/index.tsx

---
- https://app.asana.com/0/0/1207891810755787

:lipstick: Overflow-x in merge page solved

---

components/layout/footer/index.tsx
components/layout/footer/social-link.data.ts
components/layout/footer/social-link.types.ts

---
- https://app.asana.com/0/0/1208041991723873

Feat new footer

---

views/swap/input/from-input.tsx
views/swap/input/slider.tsx
views/swap/swap.types.ts

---
- https://app.asana.com/0/0/1208068380096458

🐛 Real time slider

---

views/create-token/create-token-form/index.tsx

---
- https://app.asana.com/0/0/1208041991723866

:bug: Not enough sui error mapped

---

views/dca/dca-fields/index.tsx
views/dca/index.tsx
views/dca/input/select-token.tsx

---
- https://app.asana.com/0/0/1208198541150281

:bug: fix: dca layout

---

views/dca/dca-preview-modal/index.tsx

---
- https://app.asana.com/0/0/1208198541150275

:bug: fix: dca input display

---

views/create-token/create-token-form/create-token-button.tsx
views/create-token/create-token-form/index.tsx
views/create-token/create-token.types.ts

---
- https://app.asana.com/0/0/1208213350586522

:bug: Re-render on create token solved

---

pages/dca/index.tsx
views/dca/dca-preview-modal/dca-preview-modal-summary.tsx
views/dca/dca-preview-modal/dca-preview-modal-summary.utils.ts
views/dca/dca-preview-modal/index.tsx

---
- https://app.asana.com/0/0/1208198541150275

:recycle: refactor: dca preview modal

---

views/dca/dca-preview-modal/index.tsx

---
- https://app.asana.com/0/0/1208271169091157
- https://app.asana.com/0/0/1208304518832530

:recycle: Refactor DCA preview modal buttons

---

views/dca/input/select-token.tsx

---
- https://app.asana.com/0/0/1208346607240823

:bug: Same coin fixed

---

views/dca/dca-recent-orders/dca-recent-orders-item.tsx

---
- https://app.asana.com/0/0/1208198541150281

:bug: fix: loading skeletons fixed

---

views/dca/preview-dca-button.tsx

---
- https://app.asana.com/0/0/1208346607240844

:bug: Preview button disabled without price

---

views/dca-orders/dca-order-list-item.tsx
views/dca-orders/dca-orders.data.ts

---
- https://app.asana.com/0/0/1208346607240831

:sparkles: feat: delete dca modal confirmation

---

views/dca-orders/dca-order-list-item.tsx
views/dca-orders/dca-orders.data.ts

---
- https://app.asana.com/0/0/1208346607240831

:bug: fix: dca messages

---

components/layout/index.tsx
components/layout/sidebar/sidebar.utils.ts
views/error/index.tsx

---
- https://app.asana.com/0/0/1208346607332313

:sparkles: Show 404 on wrong network page

---

components/dialog/dialog.data.ts
components/dialog/dialog.types.ts
components/dialog/index.tsx
components/index.ts
components/svg/chevron-double-left.tsx
components/svg/index.ts
hooks/use-dialog/index.tsx
hooks/use-dialog/use-dialog.types.ts
views/swap/swap-button.tsx

---
- https://app.asana.com/0/0/1208470331221324

:sparkles: Swap success modal info updated

---

views/airdrop/airdrop-form/airdrop-common-amount-text-field.tsx
views/airdrop/airdrop-form/airdrop-common-amount-toggle.tsx
views/airdrop/airdrop-form/airdrop-custom-amount-method.tsx
views/airdrop/airdrop-form/airdrop-custom-amount-text-area.tsx
views/airdrop/airdrop.types.ts
views/airdrop/airdrop.utils.ts

---
- https://app.asana.com/0/0/1208271169091157

✨ Add amount for each and for all

---

components/dialog/index.tsx
views/swap/swap-button.tsx

---
- https://app.asana.com/0/0/1208483778695032

:sparkles: Swap success modal info updated 2.0

---

components/layout/index.tsx

---
- https://app.asana.com/0/0/1208346607332313

:bug: 404 page solved

---

components/dialog/index.tsx
views/swap/swap-button.tsx

---
- https://app.asana.com/0/0/1208483778695032

:sparkles: Swap success modal updated

---

components/layout/index.tsx

---
- https://app.asana.com/0/0/1208346607332313

:bug: 404 page solved on dca order

---

views/swap/input/select-token.tsx
views/swap/swap-flip-token.tsx
views/swap/swap-init-manager.tsx

---
- https://app.asana.com/0/0/1208346607332340

:sparkles: New Swap Short URL

---

views/components/success-modal/index.tsx
views/components/success-modal/success-modal-token-card.tsx
views/components/success-modal/success-modal.types.ts
views/dca-orders/dca-order-list-item.tsx
views/dca/dca-button.tsx
views/dca/dca.types.ts
views/merge/merge-button.tsx
views/merge/merge.hooks.ts
views/merge/merge.types.ts
views/swap/swap-button.tsx

---
- https://app.asana.com/0/0/1208505451725533

:recycle: All Success Modal Changed

---

views/dca-orders/dca-order-details/dca-order-details-overview-line.tsx
views/dca-orders/dca-order-details/dca-order-details-overview.tsx
views/dca-orders/dca-orders.types.ts

---
- https://app.asana.com/0/0/1208599220114864

:fire: DCA Order with new fields

---

views/dca/dca-fields/index.tsx
views/dca/input/header-info.tsx
views/dca/input/select-token.tsx

---
- https://app.asana.com/0/0/1208599220114858

:lipstick: DCA UI Improvements

---

views/dca/dca-fields/index.tsx
views/dca/input/select-token.tsx

---
- https://app.asana.com/0/0/1208599220114858

:bug: fix: ui fixes
